FROM python:3.12-slim

WORKDIR /opt/defenseops-lab

COPY ids_tool.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt || echo "No requirements"

VOLUME ["/opt/defenseops-lab/logs"]

ENTRYPOINT ["python3", "ids_tool.py"]
