FROM python:3.12-slim

WORKDIR /opt/defenseops-lab

COPY vuln_db_tool.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt || echo "No requirements"

VOLUME ["/opt/defenseops-lab/databases"]

ENTRYPOINT ["python3", "vuln_db_tool.py"]
