FROM python:3.12-slim

WORKDIR /opt/defenseops-lab

COPY incident_response_tool.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt || echo "No requirements"

VOLUME ["/opt/defenseops-lab/reports"]

ENTRYPOINT ["python3", "incident_response_tool.py"]
